# Generated by Django 4.1 on 2024-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=255, verbose_name='Eng')),
                ('rus', models.CharField(max_length=255, verbose_name='Rus')),
            ],
        ),
    ]
